---
# vars file for tomereli.proxy
oh_my_zsh_theme: powerlevel10k

# Default plugins
oh_my_zsh_plugins:
  - git
  - docker
  - docker-compose
  - cp
  - fzf
  - thefuck
  - zsh-completions
  - gitignore
  - zsh-z
  - zsh-syntax-highlighting
  - zsh-autosuggestions
  - sudo

oh_my_zsh_aliases:
  - alias zshconfig="nano ~/.zshrc"
  - alias update='sudo apt-get update && sudo apt-get upgrade -y && sudo apt-get dist-upgrade && sudo apt-get autoremove'
  - alias install='sudo apt install'
  - alias sdn='shutdown now'
  - alias bat='batcat'
