- name: Ensure fonts directory
  become_user: "{{ item }}"
  loop: "{{ users }}"
  file:
    path: "{{ lookup('env', 'HOME') }}/.fonts"
    state: directory

- name: Hack exists
  become_user: "{{ item }}"
  loop: "{{ users }}"
  shell: "ls {{ lookup('env', 'HOME') }}/.fonts/Hack*Nerd*Font*Complete*"
  register: hack_exists
  ignore_errors: true

- name: Download Hack
  become_user: "{{ item }}"
  loop: "{{ users }}"
  when: hack_exists is failed
  ansible.builtin.unarchive:
    src: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/Hack.zip
    dest: "{{ lookup('env', 'HOME') }}/.fonts/"
    remote_src: true
