---
# tasks file for kerjox.ufw-docker
- name: Cloning ufw-docker repo 1/2
  become: true
  get_url:
    url: https://github.com/chaifeng/ufw-docker/raw/master/ufw-docker
    dest: /usr/local/bin/ufw-docker
    mode: 'u=rwxr,g=xr,o=rx'

- name: Installing ufw-docker 2/2
  become: true
  shell: ufw-docker install